/*
- DEFINIR QUÉ ENTIDADES
- NOMBRE DE LA TABLA: AUTORES
- ¿QUÉ TIPO DE INFORMACIÓN VOY A DEFINIR DE LA ENTIDAD? EJ: NOMBRE, GENERO, FECHA NACIMIENTO, PAÍS DE ORIGEN (ESTAS SON COLUMNAS)

LAS COLUMNAS SE CREAN A PARTIR DE LA INFO A ALMACENAR SEGUIDO DE SU TIPO DE DATO
*/
DROP DATABASE IF EXISTS libreria_cf;

CREATE DATABASE IF NOT EXISTS  libreria_cf;

USE libreria_cf;

CREATE TABLE autores (

    autor_id INT, -- LLAVE PRIMARIA, INT ALMACENA NÚMEROS ENTEROS
    nombre VARCHAR(50), -- VARCHAR PERMITE ALMACENAR STRING DE 0 A 65535 CARACTERES, PUEDES LIMITAR LA CANTIDAD AÑADIENDO SU VALOR EN EL PARÁMETRO, EJ 50
    apellido VARCHAR(50),
    genero CHAR(1), -- IGUAL A VARCHAR, CHAR (CADENA ALFANUMERICA) PERO CON MENOR CANTIDAD DE CARACTERES 0 A 255 CARACTERES, EN EL PARÁMETRO 1, GENERO M O F
    fecha_nacimiento DATE, -- DATE ALMACENA FECHA, FORMATO AÑO, MES, DÍA
    pais_origen VARCHAR(40) 

);

DESC autores;

-- INSERTAR AUTOR 1
INSERT INTO autores (autor_id, nombre, apellido, genero, fecha_nacimiento, pais_origen) 
VALUES (1, "Yonier", "Asprilla", "M", "1991-11-17", "COL"),
       (2, "Manuel", "Gomez", "M", "1992-12-19", "USA"),
       (3, "Iris", "Sanchez", "F", "1973-02-09", "COL");

SELECT * FROM autores;